title: <p align="center">Karan Pandey</p>
logo: /assets/img/Profile.gif
description:
  <p align="center">
  <a href="pdf/Resume_Karan.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sajan-kedia-b06a6821/">LinkedIn</a> |
  <a href="https://github.com/sajankedia">GitHub</a>
  
  <br>   
  Technical Program Manager, with 13 years’ rich experience with a strong record of contributions in managing IT projects, 
  delivery, invigorating businesses, heightening productivity, and streamlining systems & procedures while leading & implementing complex programs
<br>
  </p>
theme: jekyll-theme-minimal
