title: Karan Pandey
logo: /assets/img/Profile.gif
description: Technical Program Manager, with 13 years’ rich experience with a strong record of contributions in managing IT projects, 
  delivery, invigorating businesses, heightening productivity, and streamlining systems & procedures while leading & implementing complex programs
theme: jekyll-theme-minimal
